AnalysisJobs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('job.urls', 'job'), namespace='job'))
]

job/urls.py
# coding=utf-8
'''
*************************
file:       AnalysisJobs urls
author:     gongyi
date:       2019/7/13 16:16
****************************
change activity:
            2019/7/13 16:16
'''
from django.conf.urls import url
from .views import getCompany,index,index_data,analysis

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'jobs',index_data,name='index_data'),
    url(r'analysis',analysis,name='analysis'),
    url(r'company',getCompany,name='company')
    # url(r'jobs/(?P<page>\d+)', show, name='show_page'),
]

job/models.py
from django.db import models

# Create your models here.

job/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.http import JsonResponse
from django.views.generic import View
from db import DataClass
import logging
from django_redis import get_redis_connection
from django.core.paginator import Paginator
import multiprocessing,threading
from .spider.kanzhunSpider.Control import Control as kanzhunC
from .spider.bossSpider.Control import Control as bc
# Create your views here.

logger = logging.getLogger('django_console')
db_boss = DataClass.DataClass('bossDB','bossDB')
# db_kanzhun = DataClass.DataClass('kanzhunDB','kanzhunDB')

def start_kanzhun(company):
    print('看准网线程********',company)
    kc = kanzhunC(company)
    kc.main(company)

def start_boss(job,city_code):
    bc().main(job, city_code)

def index(request):
    '''
    全部用GET方式
    :param request:
    :return:
    '''
    logger.info('返回首页')
    return render(request, 'jobs2.html')

def index_data(request):
    '''
    点击查找按钮后返回查找的数据
    :param request:
    :return:
    '''
    logger.info('index_data方法，根据city和job查找数据并分页返回')

    # 对city和job的操作
    job = request.GET.get('job')
    city = request.GET.get('city')

    city_code = 'c101280600'  # 现在默认城市为深圳
    #
    #这个设置缓存应该是不用了
    if not all([job,city]):
        logger.info('初次进入，没有城市和职位，用默认值')
        city = request.session.get('job','深圳')
        job = request.session.get('city','python')
    else:
        #如果有这俩值，就设置缓存
        request.session['job'] = job
        request.session['city'] = city
    logger.info('得到的信息：' + str(city) + str(job))


    page = int(request.GET.get('page',1))
    logger.info('对处理好的数据分页并返回,当前页数：'+str(page))
    count = 7
    next = (page-1) * 7    #后一页的数据
    import math
    page_count = math.ceil(len(list(db_boss.connM.find({'job': {'$regex':job,'$options':'i'}, 'city': city})))/count)   #数据库中总页数

    if page_count < 5:
        page_counts = range(1, page_count + 1)
    elif page <= 3:
        page_counts = range(1, 6)
    elif page_count - page <= 2:
        page_counts = range(page_count - 4, page_count + 1)
    else:
        page_counts = range(page - 2, page + 3)
    # city = '深圳'
    # job = 'python'
    # 根据job和city信息取出数据库中的数据
    data_boss = list(db_boss.connM.find({'job': {'$regex':job,'$options':'i'}, 'city': city}).limit(count).skip(next))
    logger.info('获得了' + str(len(data_boss)) + '条数据')



    # if (len(data_boss) == 0):
    #     # 如果没取到数据，启动boss直聘爬虫
    #     logger.info('数据库中没数据，开始boss直聘爬虫进程')
    #     bc().main(job, city_code)
    #     # p = multiprocessing.Process(target=start_boss,args=(job,city_code,))
    #     # p.start()
    #     # t1 = threading.Thread(target=start_boss,args=(job,city_code,))
    #     # t1.start()
    #
    # else:
    #     # 这里应该加上对现有数据准确性的核对
    #     pass

    # 建立对于mongdb中看准网数据的连接
    db_kanzhun = DataClass.DataClass('kanzhunDB')

    # 处理数据，与看准网数据进程匹配。根据是否有能力标签，计算匹配程度
    for i in data_boss:
        # 取出公司信息根据公司名称取出看准网数据，没有就启动爬虫
        company = i['content'][2]



        # if company not in db_kanzhun.connM1.collection_names():
            # 公司名称不存在与看准网数据库的集合名中，说明没数据，启动看准网爬虫
            # logger.info('开始启动看准网爬虫进程，爬取' + company + '的数据')
            # kanzhunC(company).main(company)  # 第一个company是在爬虫内部建立根据公司名命名的collection集合
            # p2 = multiprocessing.Process(target=start_kanzhun,args=(company,))
            # t2 = threading.Thread(target=start_kanzhun,args=(company,))
            # t2.start()



        # context['salary'] = i['content'][1]
        logger.info(company)
        # 这时候，已经有数据了，开始对看准网数据进行梳理
        data_kanzhun = db_kanzhun.connM1[company].find({'title': 'company'})
        logger.info('取出看准网相关数据')

        if data_kanzhun.count() > 0:
            # 数据库里有公司相关的数据
            if 'companyScore' not in data_kanzhun[0]:
                # 没有公司评分
                company_score = None
            else:
                company_score = data_kanzhun[0]['companyScore']

            if 'interviewDegree' not in data_kanzhun[0]:
                interview_degree = None
            else:
                interview_degree = data_kanzhun[0]['interviewDegree']

            # 读取工作jd
            jd = i['content'][-1]

            i['company_score'] = company_score
            i['interview'] = interview_degree

        else:
            # 数据库中有这个公司的数据集合，但是为空。说明该公司在看准网上没数据
            i['company_score'] = '看准网没数据'
            i['interview'] = '看准网没数据'





    context = {
        'data_boss': data_boss,  # 职位数据
        'page':page,              #当前页码
        'page_counts':page_counts,   #分页范围
        'page_count':page_count      #总页数
    }

    return render(request, 'jobs.html', context)

def analysis(request):
    '''
    ajax后台方法，进行匹配指数计算和推荐指数计算并返回
    :return:
    '''
    logger.info('analysis方法开始调用')

    conn = get_redis_connection('default')  # 按照预先的配置连接redis
    tags = request.POST.get('tags')
    logger.info('&&&&&&&&&&&&&&&当前标签非缓存中是：' + str(tags))
    if not tags:
        tags = conn.smembers('tags')
        logger.info('&&&&&&&&&&&&&&&当前标签是：'+str(tags))
    else:
        logger.info('得到前台传过来的数据' + str(type(tags)))
        tag = tags.split(',')
        # 将解析成列表的标签遍历加入redis的列表中
        for i in tag:
            conn.sadd('tags', i)

    db_kanzhun = DataClass.DataClass('kanzhunDB')
    # 对city和job的操作
    job = request.GET.get('job')
    city = request.GET.get('city')
    city_code = 'c101280600'  # 现在默认城市为深圳
    #

    if not all([job, city]):
        logger.info('初次进入，没有城市和职位，读取缓存值')
        job = request.session.get('job', 'python')
        city = request.session.get('city', '深圳')
    else:
        # 如果有这俩值，就设置缓存
        request.session['job'] = job
        request.session['city'] = city
    logger.info('得到的信息：' + str(city) + str(job))

    # city = '深圳'
    # job = 'python'
    # 根据job和city信息取出数据库中的数据
    page = int(request.GET.get('page', 1))
    logger.info('对处理好的数据分页并返回,当前页数：'+str(page))
    count = 7
    next = (page - 1) * 7  # 后一页的数据
    import math
    page_count = math.ceil(
        len(list(db_boss.connM.find({'job': {'$regex': job, '$options': 'i'}, 'city': city}))) / count)  # 数据库中总页数

    if page_count < 5:
        page_counts = range(1, page_count + 1)
    elif page <= 3:
        page_counts = range(1, 6)
    elif page_count - page <= 2:
        page_counts = range(page_count - 4, page_count + 1)
    else:
        page_counts = range(page - 2, page + 3)
    # city = '深圳'
    # job = 'python'
    # 根据job和city信息取出数据库中的数据
    data_boss = list(
        db_boss.connM.find({'job': {'$regex': job, '$options': 'i'}, 'city': city}).limit(count).skip(next))
    logger.info('获得了' + str(len(data_boss)) + '条数据')

    for i in data_boss:
        company = i['content'][2]
        data_kanzhun = db_kanzhun.connM1[company].find({'title': 'company'})
        if data_kanzhun.count() > 0:
            if 'companyScore' not in data_kanzhun[0]:
                company_socre = 0
            else:
                company_socre = data_kanzhun[0]['companyScore']
            if 'interviewDegree' in data_kanzhun[0]:
                interview_degree = data_kanzhun[0]['interviewDegree']
            else:
                interview_degree = 0

            # 遍历工作信息
            jd = i['content'][-1]
            # 利用match方法匹配
            match_score = match(jd, tags)
            logger.info('匹配程度是：' + str(match_score))


            logger.info('当前公司：' + str(company) + ':' + str(company_socre) + str(interview_degree) + str(match_score))
            recommended = recommend(match_score, interview_degree, company_socre)

            i['match'] = match_score
            i['recommend'] = recommended
        else:
            i['match'] = '看准网无信息'
            i['recommend'] = '看准网无信息'

    logger.info('analysis开始返回数据')
    context = {
        'page': page,  # 当前页
        'page_count': page_count,  # 总页数
        'page_counts':page_counts,  #分页范围
        'data_boss': data_boss,  # 职位数据
    }

    return render(request,'jobs1.html',context)

def match(jd,tags):
    '''
    根据关键词匹配简历和公司情况得出匹配程度
    :param jd:招聘要求，字符串
    :param tags:集合，能力标签
    :return:
    '''
    logger.info('开始计算匹配程度'+str(tags))
    N = len(tags)
    if N==0:
        return 0
    count = 0
    for i in tags:
        if str(i) in jd:
            count += 1
    return round(count/N)


def recommend(match_score,interview_degree,company_socre):
    '''
    计算公司推荐指数
    :param match: 能力匹配程度
    :param interview: 面试难度
    :param review: 公司评分
    :return:
    '''
    recommended = 0.0
    logger.info('开始计算推荐指数')
    # 计算推荐指数。公司评分*0.8 + 面试难度 * 0.1 + 匹配程度 * 0.1
    # 匹配程度无，即未输入能力值标签时，面试难度权重为0.2
    if not company_socre:
        recommended = float(interview_degree) * 0.1 + float(match_score) * 0.9
    elif not interview_degree or interview_degree == 'None':
        recommended = float(company_socre) * 0.8 + float(match_score) * 0.2
    elif not match_score:
        recommended = float(company_socre) * 0.9 + float(interview_degree) * 0.1
    else:
        recommended = float(company_socre) * 0.8 + float(interview_degree) * 0.1 + float(match_score) * 0.1
    return round(recommended,2)


#展示公司详情
def getCompany(request):
    '''
    展示工作详情、公司评价和面试
    :param request:附带参数公司名字，工作jobId
    :return:公司评价、面试经验，工作jd
    '''
    logger.info('开始展示公司详情')
    jobId = request.GET.get('jobId')
    company = request.GET.get('company')
    logger.info('获得数据'+str(jobId)+company)
    data_boss = list(db_boss.connM.find({'jobId':jobId}))
    company_interview = list(DataClass.DataClass('kanzhunDB').connM1[company].find({'title': 'interview'},{'_id':0,'title':0}))
    company_review = list(DataClass.DataClass('kanzhunDB').connM1[company].find({'title': 'review'},{'_id':0,'title':0}))
    #读取标签和面试难度、公司评分等数据
    company_tags = list(DataClass.DataClass('kanzhunDB').connM1[company].find({'title': 'company'},{'companyTags':1,'_id':0}))[0]
    interview_degree = list(DataClass.DataClass('kanzhunDB').connM1[company].find({'title': 'company'},{'_id':0,'interviewDegree':1}))[0]

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap</title>
    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bootstrap-3.3.7-dist/css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="/static/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.css" rel="stylesheet">
    <link href="/static/bootstrap-table-1.15.3/dist/bootstrap-table.min.css" rel="stylesheet">
    <style type="text/css">
        .label {
            background: #1abc9c;
            border: 0;
            color: #fff;
            padding: 10px;
            border-radius: 5px;
            margin-top: 10px;
        }
    </style>
</head>
<body>
<!--导航栏部分。暂时没用，先占个位置，以后需要用时再补充-->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<!--主体部分-->
<div class="container-fluid">
	<div class="row-fluid">
		<div class="col-xs-12 col-md-6 head">
			<form class="form-search" method="get" action="job/jobs">
				<label style="">城市</label><input id="city" name="city" class="input-medium search-query" type="text" placeholder="默认深圳"/>
				<label style="">职位</label><input id="job" name="job" class="input-medium search-query" type="text" placeholder="默认python"/>
                <button id="search" type="submit" class="btn">查找</button>
			</form>

		</div>
		<div class="col-xs-12 col-md-6 head">
            <div class="row">
                <div class="col-md-2">
                    <label style=""><h5>能力标签&nbsp</h5></label>

            </div>
            <div class="col-md-8">
                <form action="job/analysis" method="POST" class="form-search" onkeydown="if(event.keyCode==13){return false;}"> {% csrf_token %}
                <input name="tags" id="tagsinputval" class="tagsinput" data-role="tagsinput" value="" placeholder="输入点击确认，最后提交"/>
                    <input type="text" value="" style="display: none">
                <button id="ok" type="submit">确认</button>
<!--                     <button id="ok" onclick="sendtags()">确认</button>-->

                </form>
            </div>
                <div class="col-md-2">

                </div>
		    </div>
		</div>
	</div>
</div>


{% block table %}

{% endblock table %}
<script type="text/javascript" src="/static/bootstrap-3.3.7-dist/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<script type="text/javascript" src="/static/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script type="text/javascript" src="/static/bootstrap-tagsinput-latest/src/bootstrap-tagsinput-angular.js"></script>
<script type="text/javascript" src="/static/bootstrap-table-1.15.3/dist/bootstrap-table.min.js"></script>
<script type="text/javascript">
        function sendtags(){
            tags = $("#tagsinputval").val();//tagsinput('items');
            params = {
                'tags':tags,
            };
            $.post('/job/analysis',params,function (data) {
                alert("post标签成功");
                window.location.href="job/analysis";
            });
        }
        function clearAll(){
            // $('input').tagsinput('removeAll');
            if(confirm("是否要全部清除？")){
            $("#tagsinputval").tagsinput('removeALL');
        }
        }
    </script>
{% block script %}{% endblock script %}
</body>
</html>

templates/jobs.html
{% extends 'base.html' %}
{% block table %}
    <!--职位列表展示-->
	<div class="row-fluid">
		<div class="span12">
			<table class="table" id="data_table">
				<thead>
					<tr>
						<th>职位编号</th>
						<th>职位名称</th>
						<th>工资范围</th>
						<th>工作地点</th>
						<th>经验要求</th>
						<th>学历要求</th>
						<th>公司名称</th>
						<th>公司评分</th>
						<th>面试难度</th>
                        <th>投递简历</th>
					</tr>
				</thead>

				{% for data in data_boss %}

					<tr class="clickable-row" data-href="{% url 'job:company'%}/?id={{data.jobId}}&company={{data.content.2}} ">
						<td>{{data.jobId}}</td>
						<td>{{ data.content.0|default:'空' }}</td>
						<td>{{data.content.1|default:'空'}}</td>
						<td>{{data.content.3}}</td>
						<td>{{data.content.4}}</td>
						<td>{{data.content.5}}</td>
						<td id="company">{{data.content.2}}</td>
						<td id="match">{{data.company_score}}</td>
						<td id="recommend">{{data.interview}}</td>
						<td><a href="/job/company/?company={{data.content.2}}&jobId={{data.jobId}}" class="button">查看详情</a></td>
					</tr>
				{% endfor %}
			</table>
		</div>
	</div>

</div>

<div class="container" style="text-align: center">
    <footer class="bottom">
    <ul class="pagination">
		<li>
			<a href="{% url 'job:index_data' %}?city={{request.session.city}}&job={{request.session.job}}&page=1">第一页</a>
		</li>
        <li>
        {% if page > 1 %}
        <a href="{% url 'job:index_data' %}?city={{request.session.city}}&job={{request.session.job}}&page={{page|add:'-1'}}">上一页</a>
            {% else %}
            <a href="#">上一页</a>
        {% endif %}
        </li>

        {% for p in page_counts %}
            {% if p == page %}
        <li class="active"><a href="{% url 'job:index_data' %}?city={{request.session.city}}&job={{request.session.job}}&page={{p}}">{{p}}</a>
            {% else %}
        <li><a href="{% url 'job:index_data' %}?city={{request.session.city}}&job={{request.session.job}}&page={{p}}">{{p}}</a></li>
            {% endif  %}
        {% endfor %}

        <li>
        {% if page < page_count %}
        <a href="{% url 'job:index_data' %}?city={{request.session.city}}&job={{request.session.job}}&page={{page|add:'1'}}">下一页</a>
            {% else %}
            <a href="#">下一页</a>
        {% endif %}
        </li>
		<li>
			<a href="{% url 'job:index_data' %}?city={{request.session.city}}&job={{request.session.job}}&page={{page_count}}">最后一页</a>
		</li>
    </ul>
        </footer>
</div>



{% endblock table %}

<script src="/static/bootstrap-3.3.7-dist/js/jquery-1.12.4.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<script src="/static/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script src="/static/bootstrap-tagsinput-latest/src/bootstrap-tagsinput-angular.js"></script>
<script type="text/javascript">
        function sendtags(){
            tags = $("#tagsinputval").val();//tagsinput('items');
            params = {
                'tags':tags,
            };
            $.get('/job/analysis',params,function (data) {
            	alert('分析成功');
            });
        }
        function clearAll(){
            // $('input').tagsinput('removeAll');
            if(confirm("是否要全部清除？")){
            $("#tagsinputval").tagsinput('removeALL');
        }
        }
    </script>

</body>
</html>

templates/jobs1.html
{% extends 'base.html' %}

{% block table %}
<div class="row-fluid">
		<div class="span12">
			<table class="table" id="data_table">
				<thead>
					<tr>
						<th>职位编号</th>
						<th>职位名称</th>
						<th>工资范围</th>
						<th>工作地点</th>
						<th>经验要求</th>
						<th>学历要求</th>
						<th>公司名称</th>
						<th>匹配程度</th>
						<th>推荐指数</th>
                        <th>投递简历</th>
					</tr>
				</thead>
        <tbody>
        {% for data in data_boss %}

					<tr class="clickable-row" data-href="{% url 'job:company'%}/?id={{data.jobId}}&company={{data.content.2}} ">
						<td>{{data.jobId}}</td>
						<td>{{ data.content.0|default:'空' }}</td>
						<td>{{data.content.1|default:'空'}}</td>
						<td>{{data.content.3}}</td>
						<td>{{data.content.4}}</td>
						<td>{{data.content.5}}</td>
						<td id="company">{{data.content.2}}</td>
						<td id="match">{{data.match}}</td>
						<td id="recommend">{{data.recommend}}</td>
						<td><a href="/job/company/?company={{data.content.2}}&jobId={{data.jobId}}" class="button">查看详情</a></td>
					</tr>
				{% endfor %}
        </tbody>
    </table>
    </div>
</div>


<div class="container" style="text-align: center">
    <footer class="bottom">
    <ul class="pagination">
		<li>
			<a href="{% url 'job:analysis' %}?city={{request.session.city}}&job={{request.session.job}}&page=1">第一页</a>
		</li>
        <li>
        {% if page > 1 %}
        <a href="{% url 'job:analysis' %}?city={{request.session.city}}&job={{request.session.job}}&page={{page|add:'-1'}}">上一页</a>
            {% else %}
            <a href="#">上一页</a>
        {% endif %}
        </li>

        {% for p in page_counts %}
            {% if p == page %}
        <li class="active"><a href="{% url 'job:analysis' %}?city={{request.session.city}}&job={{request.session.job}}&page={{p}}">{{p}}</a>
            {% else %}
        <li><a href="{% url 'job:analysis' %}?city={{request.session.city}}&job={{request.session.job}}&page={{p}}">{{p}}</a></li>
            {% endif  %}
        {% endfor %}

        <li>
        {% if page < page_count %}
        <a href="{% url 'job:analysis' %}?city={{request.session.city}}&job={{request.session.job}}&page={{page|add:'1'}}">下一页</a>
            {% else %}
            <a href="#">下一页</a>
        {% endif %}
        </li>
		<li>
			<a href="{% url 'job:analysis' %}?city={{request.session.city}}&job={{request.session.job}}&page={{page_count}}">最后一页</a>
		</li>
    </ul>
        </footer>
</div>{% endblock table %}
{% block script %}
<script>
    function search(){
        alert('search方法被调用');
        var url = 'job/analysis';
        var param = {
            'city':$("#city"),
            'job':$("#job"),
        };
        alert("准备执行ajax");
        $.post(url,param,function (data) {
            alert('获得数据成功');

        });
    }

    $(function () {
        $("#jobs_table").bootstrapTable({
            ajax:function (request) {
                $.ajax({
                    type:'GET',
                    url:'job/index',
                    contentType:"application/json;charset=utf-8",
                    dataType:'jsonp',
                    data:'',
                    jsonp:'callback',
                    succcess:function (msg) {
                        request.success({row:msg});
                    $("#table").bootstrapTable('load',msg);
                    },
                    error:function () {
                        alert('加载失败');
                    }
                });
            },
            cache: false, // 设置为 false 禁用 AJAX 数据缓存， 默认为true
            striped: true,  //表格显示条纹，默认为false
            pagination: true, // 在表格底部显示分页组件，默认false
            pageList: [10, 20], // 设置页面可以显示的数据条数
            pageSize: 10, // 页面数据条数
            pageNumber: 1, // 首页页码
            sidePagination: 'server', // 设置为服务器端分页
            queryParams: function (param) { // 请求服务器数据时发送的参数，可以在这里添加额外的查询参数，返回false则终止请求

          return {
              pageSize: params.limit, // 每页要显示的数据条数
              offset: params.offset, // 每页显示数据的开始行号
              sort: params.sort, // 要排序的字段
              sortOrder: params.order, // 排序规则
          }
      },
          sortName: 'id', // 要排序的字段
          sortOrder: 'desc', // 排序规则
            onLoadSuccess: function(){  //加载成功时执行
            console.info("加载成功");
      },
          onLoadError: function(){  //加载失败时执行
                console.info("加载数据失败");
          }

        })
    });

</script>
{% endblock script %}

templates/jobs2.html
{% extends 'base.html' %}
{% block table %}
    <!--职位列表展示-->
	<div class="row-fluid">
		<div class="span12">
			<table class="table" id="data_table">
				<thead>
					<tr>
						<th>职位编号</th>
						<th>职位名称</th>
						<th>工资范围</th>
						<th>工作地点</th>
						<th>经验要求</th>
						<th>学历要求</th>
						<th>公司名称</th>
						<th>匹配程度</th>
						<th>推荐指数</th>
                        <th>投递简历</th>
					</tr>
				</thead>
			</table>
		</div>
	</div>

</div>



{% endblock table %}

<script src="/static/bootstrap-3.3.7-dist/js/jquery-1.12.4.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
<script src="/static/bootstrap-tagsinput-latest/src/bootstrap-tagsinput.js"></script>
<script src="/static/bootstrap-tagsinput-latest/src/bootstrap-tagsinput-angular.js"></script>


</body>
</html>

templates/test.html
{% extends 'base.html' %}
{% block table %}
<h3>面试难度</h3>
<!--<label>公司标签</label>-->
<table>
	<thead>
	<tr>
		<td>面试人</td>
		<td>面试时间</td>
		<td>面试内容</td>
	</tr>
	</thead>
	<tbody>
	{#这里写一个循环，读取公司评价的详细内容#}
	<tr>
		<td>人</td>
		<td>时间</td>
		<td>内容</td>
	</tr>
	</tbody>
</table>
{% endblock table %}